### ISSUE TITLE
Provider does not publish config

### ISSUE THREAD

**Issue by xewl** [obuchmann/odoo-jsonrpc#1]
```sh
php artisan vendor:publish --provider="Obuchmann\OdooServiceProvider.php" --tag="config"

No publishable resources for tag [config].
```

Sidenote: This library might actually hit off, because the Ripcord/xmlrpc way is quite painful.

**Comment by xewl** [comment]
I'm actually trying to Identify models, by calling `ir.model`, `ir.model.fields` etc.

- It would be nice to be able to generate those skeletons somehow, though there are some differences between versions. (eg image_medium vs image_1024 on `product.product`)
Not sure how you're handling these, but some guidance would definitely help. (I see your examples of course)

- On v15, I'm getting an issue with a count that's being called where relation `account_aged_payable` doesn't seem to exist. If I don't ask for the field 'count', it doesn't hit this. Not sure on which level this problem exists, atm. Like, I don't even know where I'm hitting this relationship at this moment, as I just call ìr.model` to show all of it :')

**Comment by obuchmann** [comment]
If you plan to support multiple Odoo version it might be better to not rely on the Model interface but to use the Odoo api directly via the $odoo->model('sale.order'). See https://github.com/obuchmann/odoo-jsonrpc/blob/main/tests/OdooTest.php for examples.
Per default it returns all model fields and can be limited by calling ->fields(['name', 'display_name']) etc.

You can ask for the current odoo version via $odoo->version();

The Key attribute indicates that this is a Foreign relation property. When reading from Odoo the api returns an array with [id, name] for this relations. With the Key attribute only the id is stored and the name property is skipped.

Pagination would indeed be a nice feature. You may create a new issue for that.

**Comment by xewl** [comment]
I'm going just for v15 for now. Problem is that in the other versions, the keys are also different when using the direct call approach, so the Model approach can be nicer in the end as I can create a new set of models for that version and have something else grab the correct set of Models / fields based on the version of the connection. (v12 image_medium, v15 image_1024 etc) and create an accessor for it.

Thanks for they explanation of Key, _I see clearly now_ :)

**Comment by obuchmann** [comment]
My way to go for this would be to have a Model Class for each Version and to use laravel service container to inject the model depending on the used version. https://laravel.com/docs/8.x/container

You can use the static model Methods  SaleOrder::where(....  also from an injected Instance of this Model.

**Comment by sern2tech** [comment]
Wonderful respose @obuchmann
