### ISSUE TITLE
Additional Documentation

### ISSUE THREAD

**Issue by cgsmith** [obuchmann/odoo-jsonrpc#10]
It would be nice to have a few examples without being in Laravel. For example... documentation revolving around the RequestBuilder

**Comment by obuchmann** [comment]
@cgsmith the documentation does now also cover basic use cases. For a deeper understanding take a look at the test directory. Please come up with any questions you have!

**Comment by cgsmith** [comment]
I forgot the original reason why I opened this request. I'll close it!
