### ISSUE TITLE
Invoice PDF download

### ISSUE THREAD

**Issue by nicosalvadore** [obuchmann/odoo-jsonrpc#14]
Hello,

Is there a way to download invoices as PDF ?
According to this [forum post](https://www.odoo.com/fr_FR/forum/aide-1/how-to-download-an-invoice-file-in-pdf-format-in-odoo-16-using-python-221998), the method `invoice_print` has to be used. But I don't see how I can call it from your API.
Is there a way we can send "raw" queries ?

Thanks in advance :)

**Comment by obuchmann** [comment]
Hi @nicosalvadore,

you can extend the `Obuchmann\OdooJsonRpc\Odoo\Request\Request` class to implement custom requests. Here is a custom request i implemented.

toArray should return the required parameters for this function call

```php
<?php

namespace Domain\Odoo\Requests;

use Obuchmann\OdooJsonRpc\Odoo\Request\Request;

class ArchivePartner extends Request
{
    public function __construct(private int $partnerId)
    {
        parent::__construct('res.partner', 'action_archive');
    }

    public function toArray(): array
    {
        return [
            $this->partnerId
        ];
    }
}

```

Usage:

```
$odoo->execute(new ArchivePartner($contact));
```

**Comment by nicosalvadore** [comment]
I've managed to access the PDF data using the `ir.attachment` model.

```PHP
<?php

namespace App\Models;

use Obuchmann\OdooJsonRpc\Odoo\OdooModel;
use Obuchmann\OdooJsonRpc\Attributes\Field;
use Obuchmann\OdooJsonRpc\Attributes\Model;

#[Model('ir.attachment')]
class OdooAttachment extends OdooModel
{
    #[Field]
    public string $name;

    #[Field]
    public int $res_id;

    #[Field]
    public string $res_model;

    #[Field]
    public string $res_name;

    #[Field]
    public string $datas;
}

```

And then gathering the needed model with some `where()`clauses. The PDF content is then base64_encoded in the `datas` property, which allows me to trigger a download easily.

```PHP
 // Gather the invoice model 
$invoice = OdooInvoice::find($invoiceId);
$pdf = OdooAttachment::query()
    ->where('res_model', '=', "account.move")
    ->where('res_id', '=', $invoice->id)
    ->first();
return response()->streamDownload(function () use ($pdf) {
    echo(base64_decode($pdf->datas));
}, $pdf->name);
```

**Comment by sabanworld** [comment]
If anyone else runs into this, you can also achieve it via:
```
$pdfPath = $odoo->executeKw('account.move', 'get_portal_url', [[$invoiceId]]);
$pdfUrl = config('services.odoo.host') . $pdfPath . '&report_type=pdf';
```

This will give you a link to the invoice including an access_token, just like a customer would receive via email, except we skip one step via the `report_type=pdf` making it instantly stream the pdf.
