### ISSUE TITLE
Documentation: CastHandler

### ISSUE THREAD

**Issue by xewl** [obuchmann/odoo-jsonrpc#3]
Occurred error:
```
Cannot assign string to property App\Foo\Bar\Odoo\ProductProduct::$createDate of type ?DateTime
```

From viewing the tests it quickly became apparent that I had to register the Cast before it worked.
```php
\Obuchmann\OdooJsonRpc\Odoo::registerCast(new Odoo\Casts\DateTimeCast());
```

So not really an issue, merely a request to document later on :)

**Comment by obuchmann** [comment]
Good point. Unfortunately the documentation misses many features by now.

**Comment by obuchmann** [comment]
The documentation now covers the implemented casts and writing custom casts
