### ISSUE TITLE
Specify a specific user connected

### ISSUE THREAD

**Issue by jechazelle** [obuchmann/odoo-jsonrpc#9]
Hi,

I would like to know how can I use a specific user to write data for exemple and not use the "global" credential from .env please?

For example, create a new Partner with specific user:
```
// Create returning ID
$partner = new Partner();
$partner->name = 'Tester';
$partner->save();
```

If I execute this code, a new Partner will be create by admin:
.env
```
ODOO_HOST=http://localhost
ODOO_DATABASE=odoo_dev
ODOO_USERNAME=admin
ODOO_PASSWORD=admin
```

I would like to use a other user to the connection.

Thank you so much for your answer!

**Comment by Husky110** [comment]
Pretty easy...
```
<?php

namespace MyApp;

use Obuchmann\OdooJsonRpc\JsonRpc\Client;
use Obuchmann\OdooJsonRpc\Odoo;

class OdooConnector
{
    private array $connectionData;

    private Odoo $client;

    public function __construct(array $connectionData)
    {
        $this->connectionData = $connectionData;
        $this->client = new Odoo(
            (new Odoo\Config($this->connectionData['db'], $this->connectionData['url'], $this->connectionData['username'], $this->connectionData['password']))
        );
    }
    }
```

**Comment by obuchmann** [comment]
Hi @jechazelle,
unfortunately the odoo api does not support a sudo like behavior as the odoo core supports. 

You have to connect with the user you want to take the action with there credentials. The Updated Readme covers this use case.

Here is a small php example
```php
$odoo = new Odoo(new Odoo\Config($database, $host, $username, $password));
$odoo->connect();
```

You can often add the required data as custom arguments, e.g. the user_id on the partner which is in fact the sales person.
